# Generated by Django 4.0.5 on 2022-06-18 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='멤버'),
            preserve_default=False,
        ),
    ]
