# Generated by Django 4.0.5 on 2022-06-27 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmember',
            name='owner',
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='책 주인'),
            preserve_default=False,
        ),
    ]
