# Generated by Django 4.0.5 on 2022-09-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='password',
        ),
    ]
