# Generated by Django 4.0.5 on 2022-09-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='게시물 제목'),
        ),
    ]
