# Generated by Django 4.0.5 on 2022-06-14 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 11, 0, 39, 422089, tzinfo=utc), verbose_name='date last work'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=20, unique=True), max_length=20, verbose_name='nickname'),
        ),
    ]
