# Generated by Django 4.0.5 on 2022-06-14 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_last_active_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 11, 2, 21, 1747, tzinfo=utc), verbose_name='date last work'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='nickname'),
        ),
    ]
