# Generated by Django 4.0.5 on 2022-06-15 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_last_active_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 10, 18, 7, 953288), verbose_name='date last work'),
        ),
    ]
