# Generated by Django 4.0.5 on 2022-06-15 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 10, 20, 44, 118044), verbose_name='date last work'),
        ),
    ]
