# Generated by Django 4.0.5 on 2022-06-15 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_last_active_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 10, 42, 30, 967033), verbose_name='date last work'),
        ),
    ]
