# Generated by Django 4.0.5 on 2022-06-15 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_last_login_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='EMAIL.', max_length=64, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 23, 57, 15, 291686), verbose_name='date last work'),
        ),
    ]
