# Generated by Django 4.0.5 on 2022-06-16 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_email_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 0, 3, 17, 251055), verbose_name='date last work'),
        ),
    ]
