# Generated by Django 4.0.5 on 2022-06-18 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_board_image_board_user'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.board')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
